#!/bin/bash
#
# Usage:
#
# bash <(curl -s https://raw.githubusercontent.com/vulgo/webdriver.sh/v1.4.2/get)
#
set -eE
VERSION="1.4.2"
INSTALL_DIR="webdriver-$VERSION"
SCRIPT_FILENAME="webdriver.sh"
PATCHER_FILENAME="clover-patcher"
if [[ -d "$INSTALL_DIR" ]]; then
	rm -rf "$INSTALL_DIR"; fi
mkdir "$INSTALL_DIR"
cd "$INSTALL_DIR"
curl -s -o "$SCRIPT_FILENAME" "https://raw.githubusercontent.com/vulgo/webdriver.sh/v$VERSION/webdriver.sh"
curl -# -o "$PATCHER_FILENAME" "https://raw.githubusercontent.com/vulgo/webdriver.sh/v$VERSION/libexec/bin/clover-patcher.tar.gz"
tar -xzvf clover-patcher.tar.gz
rm clover-patcher.tar.gz
chmod +x "$SCRIPT_FILENAME"
chmod +x "$PATCHER_FILENAME"
touch .portable
printf 'webdriver.sh was downloaded to '
[[ $INSTALL_DIR = /* ]] && printf "$INSTALL_DIR" || printf "$PWD/${1#./}"
printf '%s\n' "$SCRIPT_FILENAME"
